# Generated by Django 2.0 on 2018-01-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITAssetManager', '0002_auto_20180101_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
