# Generated by Django 2.0 on 2018-01-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITAssetManager', '0004_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
