# Generated by Django 2.0 on 2018-01-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITAssetManager', '0006_auto_20180102_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('property_no', models.CharField(max_length=100)),
                ('purchase', models.DateField()),
                ('status', models.CharField(choices=[('D', 'Deployed'), ('U', 'Undeployed')], max_length=1)),
                ('warranty_date', models.DateField()),
                ('purchase_cost', models.FloatField()),
                ('brand', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('expiration_date', models.DateField()),
                ('license_key', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TangibleAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('property_no', models.CharField(max_length=100)),
                ('purchase', models.DateField()),
                ('status', models.CharField(choices=[('D', 'Deployed'), ('U', 'Undeployed')], max_length=1)),
                ('warranty_date', models.DateField()),
                ('purchase_cost', models.FloatField()),
                ('brand', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('model_no', models.CharField(max_length=50)),
                ('serial_no', models.CharField(max_length=100)),
                ('termination_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
