# Generated by Django 2.0.1 on 2018-01-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('AVAILABILITY', models.CharField(max_length=25)),
                ('FIRST_NAME', models.CharField(max_length=25)),
                ('LAST_EDITED', models.DateTimeField()),
                ('LAST_NAME', models.CharField(max_length=25)),
                ('MOOD', models.CharField(max_length=25)),
                ('SECURITY_KEY', models.CharField(max_length=25)),
                ('STATUS', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
