# Generated by Django 2.0.1 on 2018-01-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0003_remove_teachers2_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers2',
            name='AVAILABILITY',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
