# Generated by Django 2.0.1 on 2018-01-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0005_auto_20180117_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers2',
            name='ProfPic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='teachers2',
            name='AVAILABILITY',
            field=models.CharField(choices=[('AVAIL', 'Available'), ('UNAVAIL', 'Unavailable')], max_length=25),
        ),
        migrations.AlterField(
            model_name='teachers2',
            name='MOOD',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Angry', 'Angry')], max_length=25),
        ),
    ]
