# Generated by Django 2.0.1 on 2018-01-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0006_auto_20180117_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers2',
            name='AVAILABILITY',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=25),
        ),
    ]
