# Generated by Django 2.0.1 on 2018-01-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0007_auto_20180119_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers2',
            name='AVAILABILITY',
            field=models.CharField(choices=[('Not Set', 'Not Set'), ('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=25),
        ),
        migrations.AlterField(
            model_name='teachers2',
            name='MOOD',
            field=models.CharField(choices=[('Not Set', 'Not Set'), ('Happy', 'Happy'), ('Angry', 'Angry')], max_length=25),
        ),
    ]
