# Generated by Django 2.0.1 on 2018-01-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0008_auto_20180119_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers2',
            name='LAST_EDITED',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
