# Generated by Django 2.0.1 on 2018-01-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0010_auto_20180119_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers2',
            name='AVAILABILITY',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='teachers2',
            name='MOOD',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
