# Generated by Django 2.0.1 on 2018-01-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0011_auto_20180129_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers2',
            name='STATUS',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
