# Generated by Django 2.0.1 on 2018-01-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0012_auto_20180130_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers2',
            name='STATUS',
            field=models.CharField(blank=True, default='No Status', max_length=50, null=True),
        ),
    ]
