# Generated by Django 2.0.1 on 2018-01-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0013_auto_20180130_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(blank=True, max_length=25, null=True)),
                ('CONTENT', models.CharField(blank=True, max_length=50, null=True)),
                ('TIME_POSTED', models.DateTimeField(blank=True, null=True)),
                ('TIME_EXPIRES', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teachers2',
            name='STATUS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
