# Generated by Django 2.0.1 on 2018-02-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0014_auto_20180130_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='CONTENT',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
