# Generated by Django 2.0.1 on 2018-02-05 06:30

import HANAPP.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0017_auto_20180202_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers2',
            name='Time1',
            field=models.TimeField(blank=True, null=True, validators=[HANAPP.validators.time_validate]),
        ),
        migrations.AlterField(
            model_name='teachers2',
            name='Time2',
            field=models.TimeField(blank=True, null=True, validators=[HANAPP.validators.time_validate]),
        ),
        migrations.AlterField(
            model_name='teachers2',
            name='Time3',
            field=models.TimeField(blank=True, null=True, validators=[HANAPP.validators.time_validate]),
        ),
        migrations.AlterField(
            model_name='teachers2',
            name='Time4',
            field=models.TimeField(blank=True, null=True, validators=[HANAPP.validators.time_validate]),
        ),
        migrations.AlterField(
            model_name='teachers2',
            name='Time5',
            field=models.TimeField(blank=True, null=True, validators=[HANAPP.validators.time_validate]),
        ),
    ]
