# Generated by Django 2.0.1 on 2018-03-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANAPP', '0023_auto_20180207_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers2',
            name='AVAILABILITY',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
